global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'adamelkt96@gmail.com'
    from: 'alertmanager@example.com'
    smarthost: smtp.example.com:587
    auth_username: 'adamelkt96'
    auth_identity: 'your-username'
    auth_password: 'aze123'

    ##receivers:
##- name: 'email-notifications'
 ## webhook_configs:
 ## - url: 'http://mailhog:8025/api/v2/messages'