apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mouadoussallah/olympicplayers-app:v1
        env:
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_APP
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_ENV
        - name: DATABASE_URL
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config
        ports:
        - containerPort: 5000