---
- name: Setup Automated Database Backup for Kubernetes
  hosts: workers
  become: yes
  vars:
    db_name: playersdb
    backup_dir: /home/mouad/backups
    cron_minute: "0"
    cron_hour: "2"

  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: mouad
        group: mouad
        mode: '0755'

    - name: Copy backup script
      copy:
        content: |
          #!/bin/bash
          DATE=$(date +"%Y%m%d_%H%M%S")
          BACKUP_FILE="{{ backup_dir }}/{{ db_name }}_${DATE}.sql"
          POSTGRES_POD=$(microk8s kubectl get pods -l app=postgres -o jsonpath="{.items[0].metadata.name}")
          microk8s kubectl exec -i $POSTGRES_POD -- pg_dump -U postgres -d {{ db_name }} > $BACKUP_FILE
          if [ $? -eq 0 ]; then
            gzip $BACKUP_FILE
            find {{ backup_dir }} -name "{{ db_name }}_*.sql.gz" -type f -mtime +7 -delete
            echo "Backup completed successfully: ${BACKUP_FILE}.gz"
          else
            echo "Backup failed" >&2
          fi
        dest: /usr/local/bin/backup_db.sh
        mode: '0755'
        owner: mouad
        group: mouad

    - name: Setup cron job for backup
      cron:
        name: "Kubernetes Database Backup"
        minute: "{{ cron_minute }}"
        hour: "{{ cron_hour }}"
        job: "/usr/local/bin/backup_db.sh"
        user: mouad

    - name: Ensure microk8s group exists
      group:
        name: microk8s
        state: present

    - name: Add mouad user to microk8s group
      user:
        name: mouad
        groups: microk8s
        append: yes

    - name: Install 'at' package
      apt:
        name: at
        state: present
        update_cache: yes

    - name: Ensure 'atd' service is running
      service:
        name: atd
        state: started
        enabled: yes

    - name: Schedule immediate backup using at
      at:
        command: /usr/local/bin/backup_db.sh
        count: 1
        units: minutes
      become: yes
      become_user: mouad

    - name: Trigger backup script (asynchronous)
      command: /usr/local/bin/backup_db.sh
      async: 3600
      poll: 0
      become: yes
      become_user: mouad