---
- hosts: master
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ansible
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    # Docker and Kubernetes are now installed in the Terraform script,
    # so we don't need to handle them here.

    # You might want to add any additional configuration tasks here

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes