---
- hosts: workers
  vars_files:
    - sec_vault.yml
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        state: present

    - name: Add user to microk8s group
      user:
        name: mouad
        groups: microk8s
        append: yes

    - name: Create .kube directory
      file:
        path: /home/mouad/.kube
        state: directory
        owner: mouad
        group: mouad
        mode: '0755'

    - name: Change ownership of .kube directory
      file:
        path: /home/mouad/.kube
        owner: mouad
        group: mouad
        recurse: yes

    - name: Reset connection to allow user changes to affect ansible user
      meta: reset_connection

    - name: Wait for MicroK8s to be ready
      command: microk8s status --wait-ready
      changed_when: false
      
    - name: Enable necessary MicroK8s addons
      command: microk8s enable dns dashboard storage ingress
      changed_when: false

    - name: Create alias for kubectl
      lineinfile:
        path: /home/mouad/.bashrc
        line: 'alias kubectl="microk8s kubectl"'
        create: yes

    - name: Generate kubeconfig
      command: microk8s config
      register: kubeconfig_output
      changed_when: false

    - name: Save kubeconfig to file
      copy:
        content: "{{ kubeconfig_output.stdout }}"
        dest: /home/mouad/.kube/config
        owner: mouad
        group: mouad
        mode: '0600'

    - name: Git clone
      tags: clonecodeapp
      git:
        repo: https://{{GITHUB_USER|urlencode}}:{{GITHUB_TOKEN|urlencode}}@github.com/mouad-oussalah/Appv2.git
        dest: /home/mouad/Appv2

    - name: Ensure correct permissions for Appv2 directory
      file:
        path: /home/mouad/Appv2
        owner: mouad
        group: mouad
        recurse: yes