---
- hosts: master
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: /home/mouad/.kube
        state: directory
        owner: mouad
        group: mouad

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/mouad/.kube/config
        remote_src: yes
        owner: mouad
        group: mouad

    - name: Install Flannel network plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      become_user: mouad

    - name: Get join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Set join command fact
      set_fact:
        join_command: "{{ join_command.stdout_lines[0] }}"

- hosts: workers
  become: yes
  gather_facts: yes
  tasks:
    - name: Join cluster
      command: "{{ hostvars[groups['master'][0]]['join_command'] }} --v=5"